server:
  port: 9090

spring:
  application:
    name: mcp
  ai:
    mcp:
      server:
        name: mcp
        version: 1.0.0
        protocol: STREAMABLE
        type: SYNC
        instructions: "Personal TO-DO List service via MCP"
        tool-callback-converter: true
        tool-change-notification: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 120s

        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true

        annotation-scanner:
          enabled: true  # Enable/disable annotation scanning
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.ai.mcp: DEBUG