server:
  port: 9090

spring:
  application:
    name: mcp
  ai:
    mcp:
      server:
        name: mcp
        version: 1.0.0
        protocol: STREAMABLE
        type: SYNC
        instructions: "Personal TO-DO List service via MCP"
#        tool-callback-converter: true
        tool-change-notification: true
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 120s

        capabilities:
          tool: true
          resource: false
          prompt: false
          completion: false

        annotation-scanner:
          enabled: true  # Enable/disable annotation scanning

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/portal/kauth/oauth2/jwks
        opaquetoken:
          introspection-uri: http://localhost:8080/portal/kauth/oauth2/introspect
          client-id: admin-client
          client-secret: q1vGRFSg7YULuKPTelTb61O7bMJW5H
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.springframework.ai.mcp: DEBUG
    org.springframework.security: DEBUG
    com.konantech.mcp.config: DEBUG


mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.konantech.mcp.model,com.konantech.mcp.entity
  type-handlers-package: com.konantech.mcp.mybatis

unsplash:
  access-key: 0nWpvnLC3zfD3hsPD0g2LeEWIu00FKJ1fEyd9G2odiY
  base-url: https://api.unsplash.com

externalApiServer:
  base-url: http://localhost:9091