server:
  port: 9090

spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: mcp
        version: 0.0.1
        type: SYNC
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/messages
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
#    hibernate:
#      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    com.zaxxer.hikari: OFF
  pattern:
    console: "%msg%n"
  appenders:
    console:
      name: STDERR
      target: SYSTEM_ERR

unsplash:
  access-key: ${UNSPLASH_ACCESS_KEY:}
  base-url: https://api.unsplash.com
